[workspace]
members = [
    "apps/meow-browser",
    "apps/meow-headless",
    "crates/display-list",
    "crates/embedder-api",
    "crates/engine",
    "crates/renderer",
    "tools/xtask",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
license = "MPL-2.0"
publish = false

[workspace.dependencies]
pollster = "1.0.1"
softbuffer = { version = "0.4.8", default-features = false, features = ["wayland", "wayland-dlopen", "x11", "x11-dlopen"] }
tiny-skia = { version = "0.11.4", default-features = false, features = ["png-format", "simd"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
vello = "0.9.0"
winit = "0.30.13"

[workspace.lints.rust]
unsafe_code = "deny"
