use std::fmt::Write as _;

use meow_html::NodeId;

/// Stable identity within one generated box tree.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BoxId(pub u32);

/// Box categories generated by the W13 subset.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BoxKind {
    /// Principal block-level box generated by an element.
    PrincipalBlock,
    /// Principal inline-level box generated by an element.
    PrincipalInline,
    /// Anonymous block wrapper around a contiguous inline-level run.
    AnonymousBlock,
    /// Text content participating in an inline-level run.
    TextRun,
}

impl BoxKind {
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::PrincipalBlock => "principal-block",
            Self::PrincipalInline => "principal-inline",
            Self::AnonymousBlock => "anonymous-block",
            Self::TextRun => "text-run",
        }
    }

    #[must_use]
    pub const fn is_inline_level(self) -> bool {
        matches!(self, Self::PrincipalInline | Self::TextRun)
    }
}

/// One independent box-tree node.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BoxNode {
    pub id: BoxId,
    pub kind: BoxKind,
    pub source: Option<NodeId>,
    pub local_name: Option<String>,
    pub element_id: Option<String>,
    pub text: Option<String>,
    pub raw_text: Option<String>,
    pub children: Vec<BoxNode>,
}

/// DOM-independent formatting box tree.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct BoxTree {
    roots: Vec<BoxNode>,
}

impl BoxTree {
    pub(super) fn new(roots: Vec<BoxNode>) -> Self {
        Self { roots }
    }

    #[must_use]
    pub fn roots(&self) -> &[BoxNode] {
        &self.roots
    }

    #[must_use]
    pub fn box_by_id(&self, id: BoxId) -> Option<&BoxNode> {
        self.roots.iter().find_map(|root| find_box(root, id))
    }

    #[must_use]
    pub fn dump(&self) -> String {
        let mut output = String::new();
        writeln!(output, "#box-tree").expect("writing to String cannot fail");
        for root in &self.roots {
            dump_box(root, 0, &mut output);
        }
        output
    }
}

fn find_box(node: &BoxNode, id: BoxId) -> Option<&BoxNode> {
    if node.id == id {
        return Some(node);
    }
    node.children.iter().find_map(|child| find_box(child, id))
}

fn dump_box(node: &BoxNode, depth: usize, output: &mut String) {
    let indent = "  ".repeat(depth);
    write!(output, "{indent}{} box={}", node.kind.name(), node.id.0)
        .expect("writing to String cannot fail");
    if let Some(source) = node.source {
        write!(output, " source={}", source.slot).expect("writing to String cannot fail");
    }
    if let Some(name) = &node.local_name {
        write!(output, " name={name:?}").expect("writing to String cannot fail");
    }
    if let Some(element_id) = &node.element_id {
        write!(output, " id={element_id:?}").expect("writing to String cannot fail");
    }
    if let Some(text) = &node.text {
        write!(output, " text={text:?}").expect("writing to String cannot fail");
    }
    output.push('\n');
    for child in &node.children {
        dump_box(child, depth + 1, output);
    }
}
