[package]
name = "meow-renderer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
meow-display-list = { path = "../display-list" }
pollster.workspace = true
tiny-skia.workspace = true
vello.workspace = true
