[package]
name = "meow-browser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
default = ["js-v8"]
js-v8 = ["meow-embedder-api/js-v8", "meow-process-model/js-v8"]
js-boa = ["meow-embedder-api/js-boa", "meow-process-model/js-boa"]

[dependencies]
meow-embedder-api = { path = "../../crates/embedder-api", default-features = false }
meow-process-model = { path = "../../crates/process-model", default-features = false }
meow-inspector = { path = "../../crates/inspector" }
meow-renderer = { path = "../../crates/renderer" }
serde_json.workspace = true
softbuffer.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
winit.workspace = true
