[package]
name = "meow-browser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
meow-embedder-api = { path = "../../crates/embedder-api" }
meow-process-model = { path = "../../crates/process-model" }
meow-renderer = { path = "../../crates/renderer" }
serde_json.workspace = true
softbuffer.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
winit.workspace = true
